### PR TITLE
cvxportfolio v1.1.0

### PR DESCRIPTION
**Pull request by enzbus**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by enzbus** [comment]
@conda-forge-admin, please rerender

**Comment by enzbus** [comment]
Hi @timkpaine can you please have a look? I also updated with the documentation website. Thanks!

**Review by timkpaine — CHANGES_REQUESTED** [review]
According to:
https://github.com/cvxgrp/cvxportfolio/blob/a0a7f63b67de182d595a5dbf5e39709fbe5f18d1/pyproject.toml#L10

the dependency on `cvxpy` should not be scoped to `>=1.0.6`, and the dependency on `scipy` should be removed.

**Comment by enzbus** [comment]
You're right, it should make little difference but both should match the pyproject.toml . Thanks!

**Comment by enzbus** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
